name: Build, Test & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Building build-src
        run: |
          chmod +x ./gradlew
          ./gradlew build
        working-directory: .

      - name: Building samples/android-library
        run: |
          chmod +x ./gradlew
          ./gradlew build
        working-directory: ./samples/android-library

      - name: Building samples/js-library
        run: |
          chmod +x ./gradlew
          ./gradlew build
        working-directory: ./samples/js-library

      - name: Building samples/jvm-library
        run: |
          chmod +x ./gradlew
          ./gradlew build
        working-directory: ./samples/jvm-library

      - name: Building samples/mpp-library
        run: |
          chmod +x ./gradlew
          ./gradlew build
        working-directory: ./samples/mpp-library